name: CI
on: push

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  package:
    name: Package
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
